--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	10/24/16 12:30:03 
--  Relational Database:       	S105R9YM 
--  Standards Option:          	ISO 
CREATE TABLE TGMSDATA.FALITEM(
--  SQL150B   10   REUSEDLT(*NO) in table FALITEM in TGMSDATA ignored.
--  SQL1509   10   Format name RALITEM for FALITEM in TGMSDATA ignored.
--  SQL1506   30   Key or attribute for FALITEM in TGMSDATA ignored.
    AIORD# NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column AIORD# ignored.
    AIOSEQ NUMERIC(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column AIOSEQ ignored.
    AISHPD NUMERIC(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column AISHPD ignored.
    AISTAT CHAR(1) NOT NULL DEFAULT '' , AIITEM CHAR(12) NOT NULL DEFAULT '' , AISIZE CHAR(3) NOT
        NULL DEFAULT '' , AIWHSE CHAR(3) NOT NULL DEFAULT '' , AISOWD NUMERIC(7, 0) NOT NULL
        DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column AISOWD ignored.
    AIGLOC CHAR(3) NOT NULL DEFAULT '' , AIPHYT CHAR(1) NOT NULL DEFAULT '' , AICRDY NUMERIC(7,
        0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column AICRDY ignored.
    AICUST NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column AICUST ignored.
    AICOMP NUMERIC(2, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column AICOMP ignored.
    AIQTOA DECIMAL(11, 1) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column AIQTOA ignored.
    AIDTLA NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column AIDTLA ignored.
    AITIME NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column AITIME ignored.
    AIUSER CHAR(10) NOT NULL DEFAULT '' , AIPRCL CHAR(2) NOT NULL DEFAULT '');

GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE ON TGMSDATA.FALITEM TO EFD
    WITH GRANT OPTION;

GRANT DELETE , INSERT , SELECT , UPDATE ON TGMSDATA.FALITEM TO PUBLIC;