--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	10/24/16 12:16:41 
--  Relational Database:       	S105R9YM 
--  Standards Option:          	ISO 
CREATE TABLE TGMSDATA.FHORDR(
--  SQL150B   10   REUSEDLT(*NO) in table FHORDR in TGMSDATA ignored.
--  SQL1509   10   Format name RHORDR for FHORDR in TGMSDATA ignored.
    OHSTAT CHAR(1) NOT NULL DEFAULT '' , OHORD# NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHORD# ignored.
    OHCOMP NUMERIC(2, 0) NOT NULL DEFAULT 0 , OHCUST NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHCUST ignored.
    OHNAME CHAR(30) NOT NULL DEFAULT '' , OHSHP2 CHAR(30) NOT NULL DEFAULT '' , OHSHP3 CHAR(30)
        NOT NULL DEFAULT '' , OHSHP4 CHAR(30) NOT NULL DEFAULT '' , OHSHCT CHAR(18) NOT NULL
        DEFAULT '' , OHSHST CHAR(2) NOT NULL DEFAULT '' , OHSHZP CHAR(9) NOT NULL DEFAULT '' ,
        OHPONO CHAR(15) NOT NULL DEFAULT '' , OHDTOR NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHDTOR ignored.
    OHDTRQ NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHDTRQ ignored.
    OHDTRY DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHDTRY ignored.
    OHDTCN NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHDTCN ignored.
    OHSHIN CHAR(30) NOT NULL DEFAULT '' , OHSPIN CHAR(30) NOT NULL DEFAULT '' , OHTERM CHAR(30)
        NOT NULL DEFAULT '' , OHTRAT NUMERIC(4, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHTRAT ignored.
    OHTDAY DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHTDAY ignored.
    OHTXST CHAR(1) NOT NULL DEFAULT '' , OHTXJU CHAR(3) NOT NULL DEFAULT '' , OHAMT1 DECIMAL(9,
        2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHAMT1 ignored.
    OHAMT2 DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHAMT2 ignored.
    OHAMT3 DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHAMT3 ignored.
    OHTYPE CHAR(2) NOT NULL DEFAULT '' , OHSHPC CHAR(2) NOT NULL DEFAULT '' , OHSTA CHAR(1) NOT
        NULL DEFAULT '' , OHACK CHAR(1) NOT NULL DEFAULT '' , OHSLD1 CHAR(30) NOT NULL DEFAULT ''
        , OHSLD2 CHAR(30) NOT NULL DEFAULT '' , OHSLD3 CHAR(30) NOT NULL DEFAULT '' , OHSLD4
        CHAR(30) NOT NULL DEFAULT '' , OHSLCT CHAR(18) NOT NULL DEFAULT '' , OHSLST CHAR(2) NOT
        NULL DEFAULT '' , OHSLZP CHAR(9) NOT NULL DEFAULT '' , OHSLM1 CHAR(2) NOT NULL DEFAULT ''
        , OHSCM1 NUMERIC(4, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHSCM1 ignored.
    OHSLM2 CHAR(2) NOT NULL DEFAULT '' , OHSCM2 NUMERIC(4, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHSCM2 ignored.
    OHFRT$ DECIMAL(7, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHFRT$ ignored.
    OHMER$ DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHMER$ ignored.
    OHDIS$ DECIMAL(7, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHDIS$ ignored.
    OHMIS$ DECIMAL(7, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHMIS$ ignored.
    OHTAX$ DECIMAL(7, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHTAX$ ignored.
    OHFET$ DECIMAL(7, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHFET$ ignored.
    OHIOCD CHAR(1) NOT NULL DEFAULT '' , OHBOCD CHAR(1) NOT NULL DEFAULT '' , OHCOFL CHAR(1) NOT
        NULL DEFAULT '' , OHHOLD CHAR(1) NOT NULL DEFAULT '' , OHTDAT NUMERIC(6, 0) NOT NULL
        DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHTDAT ignored.
    OHPLPT CHAR(1) NOT NULL DEFAULT '' , OHIVCD CHAR(1) NOT NULL DEFAULT '' , OHDTLA NUMERIC(6,
        0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHDTLA ignored.
    OHTIME NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column OHTIME ignored.
    OHUSER CHAR(10) NOT NULL DEFAULT '' , OHORDY DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHORDY ignored.
    OHPPCD CHAR(1) NOT NULL DEFAULT '' , OHPRCD NUMERIC(1, 0) NOT NULL DEFAULT 0 , OHTRDC
        NUMERIC(4, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHTRDC ignored.
    OHTMCD CHAR(2) NOT NULL DEFAULT '' , OHTDAS DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHTDAS ignored.
    OHINV# NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHINV# ignored.
    OHINDT DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHINDT ignored.
    OHUPSZ CHAR(1) NOT NULL DEFAULT '' , OHFRTX CHAR(1) NOT NULL DEFAULT '' , OHSPTX CHAR(1) NOT
        NULL DEFAULT '' , OHTXID CHAR(9) NOT NULL DEFAULT '' , OHROUT CHAR(2) NOT NULL DEFAULT ''
        , OHSTOP NUMERIC(3, 0) NOT NULL DEFAULT 0 , OHARCU NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHARCU ignored.
    OHSACU NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHSACU ignored.
    OHBLCU NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHBLCU ignored.
    OHTBLK DECIMAL(11, 0) NOT NULL DEFAULT 0 , OHTBRK DECIMAL(11, 0) NOT NULL DEFAULT 0 , OHDTAC
        DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHDTAC ignored.
    OHALPH CHAR(15) NOT NULL DEFAULT '' , OHSHFR CHAR(3) NOT NULL DEFAULT '' , OHPLST CHAR(6) NOT
        NULL DEFAULT '' , OHIMED CHAR(1) NOT NULL DEFAULT '' , OHCASH DECIMAL(11, 2) NOT NULL
        DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHCASH ignored.
    OHORDT NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHORDT ignored.
    OHOLST CHAR(6) NOT NULL DEFAULT '' , OHLOC CHAR(8) NOT NULL DEFAULT '' , OHOORD NUMERIC(6, 0)
        NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHOORD ignored.
    OHDISC DECIMAL(7, 4) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OHDISC ignored.
    OHPHYT CHAR(1) NOT NULL DEFAULT '' , OHOPLP CHAR(1) NOT NULL DEFAULT '' , OHPOS CHAR(1) NOT
        NULL DEFAULT '' , OHSALE CHAR(3) NOT NULL DEFAULT '' , OHQTPR CHAR(1) NOT NULL DEFAULT ''
        , OHQUOT CHAR(1) NOT NULL DEFAULT '' , OHLOTC CHAR(1) NOT NULL DEFAULT '' , OHIMFG
        CHAR(1) NOT NULL DEFAULT '' , PRIMARY KEY(OHORD#));

GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE ON TGMSDATA.FHORDR TO EFDTST
    WITH GRANT OPTION;

GRANT DELETE , INSERT , SELECT , UPDATE ON TGMSDATA.FHORDR TO PUBLIC;