--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	10/24/16 12:22:03 
--  Relational Database:       	S105R9YM 
--  Standards Option:          	ISO 
CREATE TABLE TGMSDATA.FIORDR(
--  SQL150B   10   REUSEDLT(*NO) in table FIORDR in TGMSDATA ignored.
--  SQL1509   10   Format name RIORDR for FIORDR in TGMSDATA ignored.
    OISTAT CHAR(1) NOT NULL DEFAULT '' , OIORD# NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIORD# ignored.
    OISEQ# NUMERIC(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OISEQ# ignored.
    OIITEM CHAR(12) NOT NULL DEFAULT '' , OISIZE CHAR(3) NOT NULL DEFAULT '' , OIDES1 CHAR(30)
        NOT NULL DEFAULT '' , OIDES2 CHAR(30) NOT NULL DEFAULT '' , OICOMP NUMERIC(2, 0) NOT NULL
        DEFAULT 0 , OIWHSE CHAR(3) NOT NULL DEFAULT '' , OIBIN# CHAR(6) NOT NULL DEFAULT '' ,
        OIUUOM CHAR(2) NOT NULL DEFAULT '' , OIMULT DECIMAL(7, 4) NOT NULL DEFAULT 0 , OIUWGT
        DECIMAL(11, 4) NOT NULL DEFAULT 0 , OIUCST DECIMAL(9, 4) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIUCST ignored.
    OIUPRI DECIMAL(9, 4) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIUPRI ignored.
    OIQDDC NUMERIC(4, 2) NOT NULL DEFAULT 0 , OIEXT$ DECIMAL(9, 2) NOT NULL DEFAULT 0 , OIQORD
        DECIMAL(11, 1) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIQORD ignored.
    OIQSHP DECIMAL(11, 1) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIQSHP ignored.
    OIQBOO DECIMAL(11, 1) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIQBOO ignored.
    OISHPC CHAR(2) NOT NULL DEFAULT '' , OIAMT1 DECIMAL(7, 2) NOT NULL DEFAULT 0 , OIAMT2
        DECIMAL(7, 2) NOT NULL DEFAULT 0 , OIAMT3 DECIMAL(7, 2) NOT NULL DEFAULT 0 , OIDISC
        DECIMAL(7, 2) NOT NULL DEFAULT 0 , OISHCD CHAR(1) NOT NULL DEFAULT '' , OIOVER CHAR(1)
        NOT NULL DEFAULT '' , OIBOCD CHAR(1) NOT NULL DEFAULT '' , OISLM1 CHAR(2) NOT NULL
        DEFAULT '' , OICOM1 NUMERIC(4, 2) NOT NULL DEFAULT 0 , OISLM2 CHAR(2) NOT NULL DEFAULT ''
        , OICOM2 NUMERIC(4, 2) NOT NULL DEFAULT 0 , OICUST NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
        OIDTRQ NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIDTRQ ignored.
    OIDTLA NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIDTLA ignored.
    OITIME NUMERIC(6, 0) NOT NULL DEFAULT 0 , OIUSER CHAR(10) NOT NULL DEFAULT '' , OITRDC
        NUMERIC(4, 2) NOT NULL DEFAULT 0 , OICTCD CHAR(1) NOT NULL DEFAULT '' , OICOFL CHAR(1)
        NOT NULL DEFAULT '' , OIITYP CHAR(1) NOT NULL DEFAULT '' , OIQINV DECIMAL(11, 1) NOT NULL
        DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIQINV ignored.
    OIPLPT CHAR(1) NOT NULL DEFAULT '' , OITXCD CHAR(1) NOT NULL DEFAULT '' , OITXST CHAR(1) NOT
        NULL DEFAULT '' , OITXCT CHAR(1) NOT NULL DEFAULT '' , OITXLC CHAR(1) NOT NULL DEFAULT ''
        , OIROUT CHAR(2) NOT NULL DEFAULT '' , OISTOP NUMERIC(3, 0) NOT NULL DEFAULT 0 , OICWT
        CHAR(1) NOT NULL DEFAULT '' , OILBS# DECIMAL(11, 4) NOT NULL DEFAULT 0 , OIWGSH
        DECIMAL(11, 4) NOT NULL DEFAULT 0 , OIRSCD CHAR(1) NOT NULL DEFAULT '' , OISEQP
        NUMERIC(3, 0) NOT NULL DEFAULT 0 , OIPRAL CHAR(1) NOT NULL DEFAULT '' , OIBPUM CHAR(2)
        NOT NULL DEFAULT '' , OISUOM CHAR(2) NOT NULL DEFAULT '' , OIBLUM CHAR(2) NOT NULL
        DEFAULT '' , OIMUL2 DECIMAL(7, 4) NOT NULL DEFAULT 0 , OILOTC CHAR(1) NOT NULL DEFAULT ''
        , OIOPFL CHAR(1) NOT NULL DEFAULT '' , OIBOLN CHAR(1) NOT NULL DEFAULT '' , OIBORQ
        NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIBORQ ignored.
    OIPRBO CHAR(1) NOT NULL DEFAULT '' , OISTA CHAR(1) NOT NULL DEFAULT '' , OIINV# NUMERIC(6, 0)
        NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIINV# ignored.
    OISHFR CHAR(3) NOT NULL DEFAULT '' , OITAGS DECIMAL(9, 0) NOT NULL DEFAULT 0 , OIPPDC CHAR(1)
        NOT NULL DEFAULT '' , OIPHYT CHAR(1) NOT NULL DEFAULT '' , OISCHM CHAR(1) NOT NULL
        DEFAULT '' , OISCHS CHAR(1) NOT NULL DEFAULT '' , OIQTAL DECIMAL(11, 1) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIQTAL ignored.
    OIGLNO NUMERIC(8, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column OIGLNO ignored.
    OIITMA CHAR(15) NOT NULL DEFAULT '' , OISEDP CHAR(1) NOT NULL DEFAULT '' , OIRVCD DECIMAL(7,
        0) NOT NULL DEFAULT 0 , OIQTE CHAR(1) NOT NULL DEFAULT '' , OIORDT NUMERIC(6, 0) NOT NULL
        DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIORDT ignored.
    OIRVDT DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIRVDT ignored.
    OILOT# CHAR(10) NOT NULL DEFAULT '' , OIFRQD CHAR(1) NOT NULL DEFAULT '' , OISPFL CHAR(1) NOT
        NULL DEFAULT '' , OIALPH CHAR(15) NOT NULL DEFAULT '' , OIPRCL CHAR(2) NOT NULL DEFAULT
        '' , OINPSL CHAR(1) NOT NULL DEFAULT '' , OIRQTY DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OIRQTY ignored.
    OIPOST CHAR(1) NOT NULL DEFAULT '' , OISOW DECIMAL(7, 0) NOT NULL DEFAULT 0 , OICCDC
        DECIMAL(7, 4) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OICCDC ignored.
    OILIST CHAR(4) NOT NULL DEFAULT '' , OIROY DECIMAL(7, 2) NOT NULL DEFAULT 0 , PRIMARY
        KEY(OIORD# , OISEQ#));

GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE ON TGMSDATA.FIORDR TO EFD
    WITH GRANT OPTION;

GRANT DELETE , INSERT , SELECT , UPDATE ON TGMSDATA.FIORDR TO PUBLIC;