--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	10/24/16 12:21:16 
--  Relational Database:       	S105R9YM 
--  Standards Option:          	ISO 
CREATE TABLE TGMSDATA.FMCUST(
--  SQL150B   10   REUSEDLT(*NO) in table FMCUST in TGMSDATA ignored.
--  SQL1509   10   Format name RMCUST for FMCUST in TGMSDATA ignored.
    CMSTAT CHAR(1) NOT NULL DEFAULT '' , CMCUST NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMCUST ignored.
    CMCTYP CHAR(2) NOT NULL DEFAULT '' , CMNAME CHAR(30) NOT NULL DEFAULT '' , CMADD2 CHAR(30)
        NOT NULL DEFAULT '' , CMADD3 CHAR(30) NOT NULL DEFAULT '' , CMADD4 CHAR(30) NOT NULL
        DEFAULT '' , CMCITY CHAR(18) NOT NULL DEFAULT '' , CMSTST CHAR(2) NOT NULL DEFAULT '' ,
        CMZIP CHAR(9) NOT NULL DEFAULT '' , CMSLSM CHAR(2) NOT NULL DEFAULT '' , CMTERR CHAR(2)
        NOT NULL DEFAULT '' , CMACK CHAR(1) NOT NULL DEFAULT '' , CMPHON NUMERIC(10, 0) NOT NULL
        DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column CMPHON ignored.
    CMCNAM CHAR(30) NOT NULL DEFAULT '' , CMPTTL CHAR(8) NOT NULL DEFAULT '' , CMFNAM CHAR(12)
        NOT NULL DEFAULT '' , CMLNAM CHAR(20) NOT NULL DEFAULT '' , CMBTTL CHAR(30) NOT NULL
        DEFAULT '' , CMCRL$ DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMCRL$ ignored.
    CMTMCD CHAR(2) NOT NULL DEFAULT '' , CMCODF CHAR(1) NOT NULL DEFAULT '' , CMPRCD NUMERIC(1,
        0) NOT NULL DEFAULT 0 , CMQDIS CHAR(1) NOT NULL DEFAULT '' , CMARCD CHAR(1) NOT NULL
        DEFAULT '' , CMBOOK CHAR(1) NOT NULL DEFAULT '' , CMSMCD NUMERIC(1, 0) NOT NULL DEFAULT 0
        , CMAPLC CHAR(1) NOT NULL DEFAULT '' , CMTRDC NUMERIC(4, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMTRDC ignored.
    CMNCUS CHAR(1) NOT NULL DEFAULT '' , CMCTCD CHAR(1) NOT NULL DEFAULT '' , CMCOMM NUMERIC(4,
        2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMCOMM ignored.
    CMSHIN CHAR(30) NOT NULL DEFAULT '' , CMSPIN CHAR(30) NOT NULL DEFAULT '' , CMTXST CHAR(1)
        NOT NULL DEFAULT '' , CMTXJU CHAR(3) NOT NULL DEFAULT '' , CMFETD CHAR(1) NOT NULL
        DEFAULT '' , CMOCUR DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMOCUR ignored.
    CMOYTD DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMOYTD ignored.
    CMDTLO NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMDTLO ignored.
    CMVOPO DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMVOPO ignored.
    CMCSL$ DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMCSL$ ignored.
    CMYSL$ DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMYSL$ ignored.
    CMDTLS NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMDTLS ignored.
    CMCCS$ DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMCCS$ ignored.
    CMYCS$ DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMYCS$ ignored.
    CMARB$ DECIMAL(11, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMARB$ ignored.
    CMDTLP NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMDTLP ignored.
    CMLOOK CHAR(15) NOT NULL DEFAULT '' , CMDTLA NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMDTLA ignored.
    CMTIME NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column CMTIME ignored.
    CMUSER CHAR(10) NOT NULL DEFAULT '' , CMCOMP NUMERIC(2, 0) NOT NULL DEFAULT 0 , CMSHFR
        CHAR(3) NOT NULL DEFAULT '' , CMPORQ CHAR(1) NOT NULL DEFAULT '' , CMFILA CHAR(11) NOT
        NULL DEFAULT '' , CMTXID CHAR(9) NOT NULL DEFAULT '' , CMUPSZ CHAR(1) NOT NULL DEFAULT ''
        , CMRTE1 CHAR(2) NOT NULL DEFAULT '' , CMRTE2 CHAR(2) NOT NULL DEFAULT '' , CMRTE3
        CHAR(2) NOT NULL DEFAULT '' , CMRTE4 CHAR(2) NOT NULL DEFAULT '' , CMRTE5 CHAR(2) NOT
        NULL DEFAULT '' , CMRTE6 CHAR(2) NOT NULL DEFAULT '' , CMRTE7 CHAR(2) NOT NULL DEFAULT ''
        , CMSTP1 DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMSTP1 ignored.
    CMSTP2 DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMSTP2 ignored.
    CMSTP3 DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMSTP3 ignored.
    CMSTP4 DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMSTP4 ignored.
    CMSTP5 DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMSTP5 ignored.
    CMSTP6 DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMSTP6 ignored.
    CMSTP7 DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMSTP7 ignored.
    CMARCU NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMARCU ignored.
    CMSACU NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMSACU ignored.
    CMBLCU NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMBLCU ignored.
    CMCOPY NUMERIC(1, 0) NOT NULL DEFAULT 0 , CMJOBR CHAR(1) NOT NULL DEFAULT '' , CMORLS CHAR(6)
        NOT NULL DEFAULT '' , CMDSHF CHAR(1) NOT NULL DEFAULT '' , CMCUR$ DECIMAL(11, 2) NOT NULL
        DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMCUR$ ignored.
    CMAR1$ DECIMAL(11, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMAR1$ ignored.
    CMAR2$ DECIMAL(11, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMAR2$ ignored.
    CMAR3$ DECIMAL(11, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMAR3$ ignored.
    CMAR4$ DECIMAL(11, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMAR4$ ignored.
    CMFUT$ DECIMAL(11, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMFUT$ ignored.
    CMIREF NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column CMIREF ignored.
    CMCNME CHAR(30) NOT NULL DEFAULT '' , CMPHO2 NUMERIC(10, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column CMPHO2 ignored.
    CMBABB CHAR(5) NOT NULL DEFAULT '' , CMPHYT CHAR(1) NOT NULL DEFAULT '' , CMFILL CHAR(2) NOT
        NULL DEFAULT '' , CMSVCD CHAR(2) NOT NULL DEFAULT '' , CMCOUN CHAR(10) NOT NULL DEFAULT
        '' , PRIMARY KEY(CMCUST));

GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE ON TGMSDATA.FMCUST TO EFDTST
    WITH GRANT OPTION;

GRANT DELETE , INSERT , SELECT , UPDATE ON TGMSDATA.FMCUST TO PUBLIC;