--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	10/24/16 12:28:44 
--  Relational Database:       	S105R9YM 
--  Standards Option:          	ISO 
CREATE TABLE TGMSDATA.FMTAXF(
--  SQL150B   10   REUSEDLT(*NO) in table FMTAXF in TGMSDATA ignored.
--  SQL1509   10   Format name RMTAXF for FMTAXF in TGMSDATA ignored.
    TXSTAT CHAR(1) NOT NULL DEFAULT '' , TXTXJU CHAR(3) NOT NULL DEFAULT '' , TXJUNM CHAR(30) NOT
        NULL DEFAULT '' , TXPCT1 DECIMAL(7, 4) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TXPCT1 ignored.
    TXPCT2 DECIMAL(7, 4) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TXPCT2 ignored.
    TXPCT3 DECIMAL(7, 4) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TXPCT3 ignored.
    TXDTLA NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TXDTLA ignored.
    TXTIME NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column TXTIME ignored.
    TXUSER CHAR(10) NOT NULL DEFAULT '' , TXGLA1 NUMERIC(8, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column TXGLA1 ignored.
    TXGLA2 NUMERIC(8, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column TXGLA2 ignored.
    TXGLA3 NUMERIC(8, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTWRD in column TXGLA3 ignored.
    TXLIM1 DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TXLIM1 ignored.
    TXLIM2 DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TXLIM2 ignored.
    TXLIM3 DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TXLIM3 ignored.
    TXCOMN NUMERIC(2, 0) NOT NULL DEFAULT 0 , PRIMARY KEY(TXTXJU));

GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE ON TGMSDATA.FMTAXF TO EFDTST
    WITH GRANT OPTION;

GRANT DELETE , INSERT , SELECT , UPDATE ON TGMSDATA.FMTAXF TO PUBLIC;