--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	10/24/16 12:24:21 
--  Relational Database:       	S105R9YM 
--  Standards Option:          	ISO 
CREATE TABLE TGMSDATA.FMTERM(
--  SQL150B   10   REUSEDLT(*NO) in table FMTERM in TGMSDATA ignored.
--  SQL1509   10   Format name RMTERM for FMTERM in TGMSDATA ignored.
    TCTERM CHAR(2) NOT NULL DEFAULT '' , TCDESC CHAR(30) NOT NULL DEFAULT '' , TCTDAY DECIMAL(3,
        0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCTDAY ignored.
    TCTRAT NUMERIC(4, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCTRAT ignored.
    TCTDAS DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCTDAS ignored.
    TCTRTP NUMERIC(1, 0) NOT NULL DEFAULT 0 , TCCUTO NUMERIC(2, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCCUTO ignored.
    TCMBCO NUMERIC(2, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCMBCO ignored.
    TCDBCO NUMERIC(2, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCDBCO ignored.
    TCNBCO NUMERIC(2, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCNBCO ignored.
    TCMACO NUMERIC(2, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCMACO ignored.
    TCDACO NUMERIC(2, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCDACO ignored.
    TCNACO NUMERIC(2, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCNACO ignored.
    TCDDUE NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCDDUE ignored.
    TCNDUE NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column TCNDUE ignored.
    PRIMARY KEY(TCTERM));

GRANT DELETE , INSERT , SELECT , UPDATE ON TGMSDATA.FMTERM TO PUBLIC;

GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE ON TGMSDATA.FMTERM TO QDFTOWN
    WITH GRANT OPTION;