--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	10/24/16 12:25:53 
--  Relational Database:       	S105R9YM 
--  Standards Option:          	ISO 
CREATE TABLE TGMSDATA.FOPNORD(
--  SQL1509   10   Format name ROPNORD for FOPNORD in TGMSDATA ignored.
    OOORD# NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OOORD# ignored.
    OOCOMP NUMERIC(2, 0) NOT NULL DEFAULT 0 , OOCUST NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OOCUST ignored.
    OODTRY DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OODTRY ignored.
    OOORDY DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OOORDY ignored.
    OOARCU NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OOARCU ignored.
    OOSACU NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OOSACU ignored.
    OOBLCU NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OOBLCU ignored.
    OOSHFR CHAR(3) NOT NULL DEFAULT '' , OOEXT$ DECIMAL(9, 2) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column OOEXT$ ignored.
    PRIMARY KEY(OOORD#));

GRANT DELETE , INSERT , SELECT , UPDATE ON TGMSDATA.FOPNORD TO PUBLIC;

GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE ON TGMSDATA.FOPNORD TO QDFTOWN
    WITH GRANT OPTION;