--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	10/24/16 12:53:29 
--  Relational Database:       	S105R9YM 
--  Standards Option:          	ISO 
CREATE TABLE TGMSDATA.FPPO(
--  SQL150B   10   REUSEDLT(*NO) in table FPPO in TGMSDATA ignored.
--  SQL1509   10   Format name RPPO for FPPO in TGMSDATA ignored.
    POORD# NUMERIC(6, 0) NOT NULL DEFAULT 0 ,
--  SQL150D   10   EDTCDE in column POORD# ignored.
    POTAKN CHAR(10) NOT NULL DEFAULT '' , POENTR CHAR(10) NOT NULL DEFAULT '' , POPICK CHAR(10)
        NOT NULL DEFAULT '' , POPACK CHAR(10) NOT NULL DEFAULT '' , POCONF CHAR(10) NOT NULL
        DEFAULT '' , POLOWC CHAR(8) NOT NULL DEFAULT '' , POLOWF CHAR(8) NOT NULL DEFAULT '' ,
        POLORB CHAR(8) NOT NULL DEFAULT '' , PRIMARY KEY(POORD#));

GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE ON TGMSDATA.FPPO TO EFD
    WITH GRANT OPTION;

GRANT DELETE , INSERT , SELECT , UPDATE ON TGMSDATA.FPPO TO PUBLIC;